# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- develop
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: CmdLine@2
  inputs:
    script: 'Bundler\bin\release\Bundler.exe'

- task: GitHubRelease@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master'. 'refs/heads/develop')
  inputs:
    gitHubConnection: 'github.com_gv-15'
    repositoryName: 'gv-15/Code-S.A'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'v1.1'
    title: 'Code S.A. release'
    assets: '*.zip'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
